package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("<!-- Tailwind CSS -->\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<!-- Footer -->\n");
      out.write("<footer class=\"bg-black text-white py-16 px-6 relative\">\n");
      out.write("  <div class=\"max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-10 animate-fadeInUp\">\n");
      out.write("\n");
      out.write("    <!-- Logo + Description -->\n");
      out.write("    <div>\n");
      out.write("      <h2 class=\"text-2xl font-bold mb-3\">FoodieCanteen</h2>\n");
      out.write("      <p class=\"text-gray-300\">Delivering hot, tasty meals to your doorstep. Quick. Reliable. Delicious.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Quick Links -->\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Explore</h3>\n");
      out.write("      <ul class=\"space-y-2 text-gray-300\">\n");
      out.write("        <li><a href=\"/menu\" class=\"hover:text-white transition\">Menu</a></li>\n");
      out.write("        <li><a href=\"/offers\" class=\"hover:text-white transition\">Offers</a></li>\n");
      out.write("        <li><a href=\"/track\" class=\"hover:text-white transition\">Track Order</a></li>\n");
      out.write("        <li><a href=\"/faq\" class=\"hover:text-white transition\">FAQ</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Contact Info -->\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Contact</h3>\n");
      out.write("      <p class=\"text-gray-300\">Email: Foodie@Canteen.com</p>\n");
      out.write("      <p class=\"text-gray-300\">Phone: +91 79878 40420</p>\n");
      out.write("      <p class=\"text-gray-300 mb-4\">Bhopal, India</p>\n");
      out.write("\n");
      out.write("      <!-- Payment Logos -->\n");
      out.write("      <div class=\"flex items-center space-x-3\">\n");
      out.write("        <img src=\"https://img.icons8.com/color/48/visa.png\" class=\"w-10 h-7\" alt=\"Visa\"/>\n");
      out.write("        <img src=\"https://img.icons8.com/color/48/mastercard.png\" class=\"w-10 h-7\" alt=\"MasterCard\"/>\n");
      out.write("        \n");
      out.write("        <img src=\"https://img.icons8.com/color/48/paypal.png\" class=\"w-10 h-7\" alt=\"PayPal\"/>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Newsletter + Social -->\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Stay Updated</h3>\n");
      out.write("      <form class=\"flex flex-col sm:flex-row gap-2\">\n");
      out.write("        <input type=\"email\" placeholder=\"Your email\"\n");
      out.write("               class=\"w-full px-4 py-2 rounded bg-gray-900 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-white\">\n");
      out.write("        <button type=\"submit\" class=\"bg-white text-black px-4 py-2 rounded hover:bg-gray-300 transition\">Subscribe</button>\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("       <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Follow Us</h3>\n");
      out.write("      <div class=\"flex gap-4\">\n");
      out.write("        <a href=\"#\" class=\"transform hover:scale-125 transition-transform duration-300\" data-aos=\"zoom-in\">\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/1384/1384063.png\" alt=\"Facebook\" class=\"w-8 h-8 hover:drop-shadow-[0_0_8px_#000000]\" />\n");
      out.write("        </a>\n");
      out.write("        <a href=\"#\" class=\"transform hover:scale-125 transition-transform duration-300\" data-aos=\"zoom-in\" data-aos-delay=\"100\">\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/1384/1384060.png\" alt=\"Instagram\" class=\"w-8 h-8 hover:drop-shadow-[0_0_8px_#000000]\" />\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Footer Bottom -->\n");
      out.write("  <div class=\"text-center text-gray-400 mt-12 border-t border-gray-700 pt-6\">\n");
      out.write("    &copy; 2025 <span class=\"text-white font-semibold\">FoodieCanteen</span> | Built with Love? and hot samosas.\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Scroll To Top Button -->\n");
      out.write("  <button onclick=\"scrollToTop()\"\n");
      out.write("          class=\"fixed bottom-5 right-5 bg-white text-black p-3 rounded-full shadow-lg hover:bg-gray-200 hover:scale-110 transition duration-300 z-50\">\n");
      out.write("    <i class=\"fas fa-arrow-up\"></i>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <!-- Floating Chat Icon -->\n");
      out.write("  \n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Scroll to Top Script -->\n");
      out.write("<script>\n");
      out.write("function scrollToTop() {\n");
      out.write("  window.scrollTo({ top: 0, behavior: 'smooth' });\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- Fade-in Keyframes -->\n");
      out.write("<style>\n");
      out.write("@keyframes fadeInUp {\n");
      out.write("  from { opacity: 0; transform: translateY(40px); }\n");
      out.write("  to   { opacity: 1; transform: translateY(0); }\n");
      out.write("}\n");
      out.write(".animate-fadeInUp {\n");
      out.write("  animation: fadeInUp 1.2s ease-out both;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- FOOTER HTML \n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div class=\"footer-container\">\n");
      out.write("    <div class=\"footer-box about\">\n");
      out.write("      <h2 class=\"footer-title\">FoodDash</h2>\n");
      out.write("      <p>Delivering hot, tasty meals to your doorstep. Quick. Reliable. Delicious.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer-box links\">\n");
      out.write("      <h3>Explore</h3>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"/menu\">Our Menu</a></li>\n");
      out.write("        <li><a href=\"/offers\">Offers</a></li>\n");
      out.write("        <li><a href=\"/track\">Track Order</a></li>\n");
      out.write("        <li><a href=\"/faq\">FAQ</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer-box contact\">\n");
      out.write("      <h3>Contact</h3>\n");
      out.write("      <p>Email: hello@fooddash.com</p>\n");
      out.write("      <p>Phone: +91 98765 43210</p>\n");
      out.write("      <p>Delhi, India</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer-box social\">\n");
      out.write("      <h3>Follow Us</h3>\n");
      out.write("      <div class=\"social-icons\">\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-x-twitter\"></i></a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"footer-bottom\">\n");
      out.write("    &copy; 2025 <strong>FoodDash</strong> | Built with ? and hot samosas.\n");
      out.write("  </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write(" FONT AWESOME ICONS \n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write(" FOOTER CSS \n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("  margin: 0;\n");
      out.write("  background: #000;\n");
      out.write("  color: white;\n");
      out.write("  font-family: 'Segoe UI', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer {\n");
      out.write("  background: linear-gradient(145deg, #000000, #1a1a1a);\n");
      out.write("  color: #ffffff;\n");
      out.write("  padding: 60px 20px 30px;\n");
      out.write("  box-shadow: 0 -5px 30px rgba(255, 255, 255, 0.1);\n");
      out.write("  animation: fadeSlideUp 1.5s ease forwards;\n");
      out.write("  border-top: 2px solid #fff;\n");
      out.write("  position: relative;\n");
      out.write("  z-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-container {\n");
      out.write("  display: flex;\n");
      out.write("  flex-wrap: wrap;\n");
      out.write("  justify-content: space-around;\n");
      out.write("  max-width: 1200px;\n");
      out.write("  margin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box {\n");
      out.write("  flex: 1 1 220px;\n");
      out.write("  margin: 20px;\n");
      out.write("  transform: translateY(30px);\n");
      out.write("  animation: slideUp 1s ease forwards;\n");
      out.write("  opacity: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box:nth-child(1) { animation-delay: 0.2s; }\n");
      out.write(".footer-box:nth-child(2) { animation-delay: 0.4s; }\n");
      out.write(".footer-box:nth-child(3) { animation-delay: 0.6s; }\n");
      out.write(".footer-box:nth-child(4) { animation-delay: 0.8s; }\n");
      out.write("\n");
      out.write(".footer-title {\n");
      out.write("  font-size: 26px;\n");
      out.write("  color: #ffffff;\n");
      out.write("  margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box h3 {\n");
      out.write("  color: #ffffff;\n");
      out.write("  font-size: 18px;\n");
      out.write("  margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul {\n");
      out.write("  list-style: none;\n");
      out.write("  padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul li {\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul li a {\n");
      out.write("  color: #bbb;\n");
      out.write("  text-decoration: none;\n");
      out.write("  transition: 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul li a:hover {\n");
      out.write("  color: #fff;\n");
      out.write("  text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box p {\n");
      out.write("  color: #ccc;\n");
      out.write("  line-height: 1.6;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-icons a {\n");
      out.write("  color: #fff;\n");
      out.write("  margin-right: 15px;\n");
      out.write("  font-size: 20px;\n");
      out.write("  transition: transform 0.3s ease, color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-icons a:hover {\n");
      out.write("  color: #fff;\n");
      out.write("  transform: scale(1.3) rotate(5deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-bottom {\n");
      out.write("  text-align: center;\n");
      out.write("  margin-top: 40px;\n");
      out.write("  padding-top: 15px;\n");
      out.write("  border-top: 1px solid #444;\n");
      out.write("  font-size: 14px;\n");
      out.write("  color: #aaa;\n");
      out.write("  opacity: 0.8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes fadeSlideUp {\n");
      out.write("  from {\n");
      out.write("    opacity: 0;\n");
      out.write("    transform: translateY(40px);\n");
      out.write("  }\n");
      out.write("  to {\n");
      out.write("    opacity: 1;\n");
      out.write("    transform: translateY(0);\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes slideUp {\n");
      out.write("  to {\n");
      out.write("    transform: translateY(0);\n");
      out.write("    opacity: 1;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 768px) {\n");
      out.write("  .footer-container {\n");
      out.write("    flex-direction: column;\n");
      out.write("    align-items: center;\n");
      out.write("    text-align: center;\n");
      out.write("  }\n");
      out.write("  .footer-box {\n");
      out.write("    margin: 20px 0;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("</style>-->\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
