package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.DBConnection;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class order_005fhistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<String>(2);
    _jspx_dependants.add("/navbar.jsp");
    _jspx_dependants.add("/footer.jsp");
  }

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String userType = null;
    String userEmail = null;
    if (session != null) {
        userType = (String) session.getAttribute("userType");
        userEmail = (String) session.getAttribute("email");
    }

    Map<String, String> lastOrder = null;
    List<Map<String, String>> orderList = new ArrayList<>();
    String guestMessage = null;

    if ("guest".equalsIgnoreCase(userType) || session == null) {
        guestMessage = "First order something then see your last orders";
    } else {
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT * FROM orders WHERE email = ? ORDER BY order_time DESC"
            );
            ps.setString(1, userEmail);
            ResultSet rs = ps.executeQuery();

            boolean isFirst = true;
            while (rs.next()) {
                Map<String, String> order = new HashMap<>();
                order.put("orderId", String.valueOf(rs.getInt("id")));
                order.put("orderTime", rs.getTimestamp("order_time").toString());
                order.put("itemList", rs.getString("Food_items"));
                order.put("amount", String.format("%.2f", rs.getDouble("total_amount")));
                order.put("currentState", rs.getString("Order_status"));

                if (isFirst) {
                    lastOrder = order;
                    isFirst = false;
                } else {
                    orderList.add(order);
                }
            }

            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            guestMessage = "Error fetching orders: " + e.getMessage();
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Order History</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background: linear-gradient(to right, #2c3e50, #4ca1af);\n");
      out.write("            color: #f8f9fa;\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("        }\n");
      out.write("        .card {\n");
      out.write("            background-color: #1e1e1e;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.4);\n");
      out.write("        }\n");
      out.write("        .last-order-box {\n");
      out.write("            background-color: #343a40;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            color: #ffdd57;\n");
      out.write("            box-shadow: 0 4px 12px rgba(255, 221, 87, 0.3);\n");
      out.write("        }\n");
      out.write("        .status-label {\n");
      out.write("            font-weight: bold;\n");
      out.write("            animation: blink 1s infinite alternate;\n");
      out.write("        }\n");
      out.write("        .status-confirmed { color: #4caf50; }\n");
      out.write("        .status-preparing { color: #ff9800; }\n");
      out.write("        .status-ready { color: #2196f3; }\n");
      out.write("        @keyframes blink {\n");
      out.write("            from { opacity: 1; }\n");
      out.write("            to { opacity: 0.8; }\n");
      out.write("        }\n");
      out.write("        .table th, .table td {\n");
      out.write("            vertical-align: middle;\n");
      out.write("        }\n");
      out.write("        h2, h4 {\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Tailwind CDN -->\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("<!-- AOS (Animate on Scroll) -->\n");
      out.write("<link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"></script>\n");
      out.write("<script>\n");
      out.write("  AOS.init();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- Navbar -->\n");
      out.write("<nav class=\"fixed top-0 left-0 w-full z-50 backdrop-blur-md bg-black bg-opacity-30 shadow-xl\">\n");
      out.write("  <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\n");
      out.write("    <div class=\"flex items-center justify-between h-16\">\n");
      out.write("      <!-- Logo -->\n");
      out.write("      <a href=\"menu.jsp\" class=\"flex items-center space-x-3\">\n");
      out.write("        <img src=\"./images/png-original.png\" class=\"h-10 w-10 object-cover transform hover:scale-110 transition duration-300 ease-in-out\" alt=\"Canteen Logo\">\n");
      out.write("       \n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("      <!-- Toggle -->\n");
      out.write("      <div class=\"md:hidden\">\n");
      out.write("        <button id=\"mobile-menu-button\" class=\"text-white focus:outline-none\">\n");
      out.write("          <i class=\"fas fa-bars text-xl\"></i>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Links -->\n");
      out.write("      <div id=\"navbar-content\" class=\"hidden md:flex md:items-center space-x-6\">\n");
      out.write("        <a href=\"menu.jsp\" class=\"text-white hover:text-gray-300 transition transform hover:scale-105 duration-300\">\n");
      out.write("          <i class=\"fas fa-utensils mr-1\"></i> Menu\n");
      out.write("        </a>\n");
      out.write("        <a href=\"userDetails.jsp?tableNo=");
      out.print(session.getAttribute("tableNo"));
      out.write("\" class=\"text-white hover:text-gray-300 transition transform hover:scale-105 duration-300\">\n");
      out.write("          <i class=\"fas fa-user mr-1\"></i> Your Details\n");
      out.write("        </a>\n");
      out.write("        <a href=\"order_history.jsp\" class=\"text-white hover:text-gray-300 transition transform hover:scale-105 duration-300\">\n");
      out.write("          <i class=\"fas fa-receipt mr-1\"></i> Order Summary\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <!-- Search Bar -->\n");
      out.write("        <div class=\"relative\">\n");
      out.write("          <input type=\"text\" placeholder=\"Search...\" class=\"px-3 py-1 rounded-full bg-gray-800 text-white focus:outline-none\" id=\"searchInput\" onkeyup=\"searchMenu()\">\n");
      out.write("          <i class=\"fas fa-search absolute right-3 top-2 text-white\"></i>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Profile / Logout -->\n");
      out.write("        <div class=\"flex items-center space-x-4\">\n");
      out.write("          <div class=\"text-white bg-white bg-opacity-10 px-4 py-2 rounded-full\">\n");
      out.write("            <i class=\"fas fa-user-circle mr-1\"></i>\n");
      out.write("            <span>");
      out.print(session.getAttribute("username") != null ? session.getAttribute("username") : "Guest");
      out.write("</span>\n");
      out.write("          </div>\n");
      out.write("          <a href=\"logout.jsp\" class=\"text-white border border-white px-4 py-2 rounded-full hover:bg-white hover:text-black transition duration-300\">\n");
      out.write("            <i class=\"fas fa-sign-out-alt mr-1\"></i> Admin Login\n");
      out.write("          </a>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Mobile Menu -->\n");
      out.write("  <div id=\"mobile-menu\" class=\"md:hidden hidden bg-black bg-opacity-30 backdrop-blur-md px-4 py-4 space-y-3\">\n");
      out.write("    <a href=\"menu.jsp\" class=\"block text-white\">Menu</a>\n");
      out.write("    <a href=\"userDetails.jsp?tableNo=");
      out.print(session.getAttribute("tableNo"));
      out.write("\" class=\"block text-white\">Your Details</a>\n");
      out.write("    <a href=\"order_history.jsp\" class=\"block text-white\">Order Summary</a>\n");
      out.write("    <a href=\"logout.jsp\" class=\"block text-white\">Admin Login</a>\n");
      out.write("   \n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  document.getElementById('mobile-menu-button').addEventListener('click', () => {\n");
      out.write("    document.getElementById('mobile-menu').classList.toggle('hidden');\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("     function searchMenu() {\n");
      out.write("        const query = document.getElementById('searchInput').value.toLowerCase();\n");
      out.write("        const items = document.querySelectorAll('.menu-item');\n");
      out.write("\n");
      out.write("        items.forEach(item => {\n");
      out.write("            const name = item.dataset.name;\n");
      out.write("            const type = item.dataset.type.toLowerCase();\n");
      out.write("            item.style.display = (name.includes(query) || type.includes(query)) ? 'block' : 'none';\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        document.querySelectorAll('.category-btn').forEach(btn => btn.classList.remove('active'));\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n");
      out.write("\n");
      out.write("    <div class=\"container mt-5\">\n");
      out.write("        <div class=\"card p-5\">\n");
      out.write("            <h2 class=\"mb-4 text-warning\">Your Order History</h2>\n");
      out.write("\n");
      out.write("            ");
 if (guestMessage != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-info\">");
      out.print( guestMessage );
      out.write("</div>\n");
      out.write("            ");
 } else if (lastOrder != null) { 
      out.write("\n");
      out.write("                <h4 class=\"text-light\">Last Order</h4>\n");
      out.write("                <div class=\"last-order-box\">\n");
      out.write("                    <p><strong>Order ID:</strong> ");
      out.print( lastOrder.get("orderId") );
      out.write("</p>\n");
      out.write("                    <p><strong>Date:</strong> ");
      out.print( lastOrder.get("orderTime") );
      out.write("</p>\n");
      out.write("                    <p><strong>Items:</strong> ");
      out.print( lastOrder.get("itemList") );
      out.write("</p>\n");
      out.write("                    <p><strong>Total Amount:</strong> ₹ ");
      out.print( lastOrder.get("amount") );
      out.write("</p>\n");
      out.write("                    <p><strong>Status:</strong>\n");
      out.write("                        ");
 String status = lastOrder.get("currentState"); 
      out.write("\n");
      out.write("                        <span class=\"status-label \n");
      out.write("                            ");
      out.print( "Confirmed".equalsIgnoreCase(status) ? "status-confirmed" : "" );
      out.write("\n");
      out.write("                            ");
      out.print( "Preparing".equalsIgnoreCase(status) ? "status-preparing" : "" );
      out.write("\n");
      out.write("                            ");
      out.print( "Ready".equalsIgnoreCase(status) ? "status-ready" : "" );
      out.write("\">\n");
      out.write("                            ");
      out.print( status );
      out.write(" -\n");
      out.write("                            ");
      out.print( "Confirmed".equalsIgnoreCase(status) ? "Order placed successfully." :
                                "Preparing".equalsIgnoreCase(status) ? "Your order is being prepared." :
                                "Ready".equalsIgnoreCase(status) ? "Your order is ready for pickup." : status );
      out.write("\n");
      out.write("                        </span>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (!orderList.isEmpty()) { 
      out.write("\n");
      out.write("                    <h4 class=\"text-light mt-5\">Previous Orders</h4>\n");
      out.write("                    <table class=\"table table-dark table-hover mt-3\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>Order ID</th>\n");
      out.write("                                <th>Date</th>\n");
      out.write("                                <th>Items</th>\n");
      out.write("                                <th>Amount</th>\n");
      out.write("                                <th>Status</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                        ");
 for (Map<String, String> order : orderList) {
                            String s = order.get("currentState"); 
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td>");
      out.print( order.get("orderId") );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( order.get("orderTime") );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( order.get("itemList") );
      out.write("</td>\n");
      out.write("                                <td>₹ ");
      out.print( order.get("amount") );
      out.write("</td>\n");
      out.write("                                <td>\n");
      out.write("                                    <span class=\"status-label \n");
      out.write("                                        ");
      out.print( "Confirmed".equalsIgnoreCase(s) ? "status-confirmed" : "" );
      out.write("\n");
      out.write("                                        ");
      out.print( "Preparing".equalsIgnoreCase(s) ? "status-preparing" : "" );
      out.write("\n");
      out.write("                                        ");
      out.print( "Ready".equalsIgnoreCase(s) ? "status-ready" : "" );
      out.write("\">\n");
      out.write("                                        ");
      out.print( s );
      out.write(" -\n");
      out.write("                                        ");
      out.print( "Confirmed".equalsIgnoreCase(s) ? "Order placed successfully." :
                                            "Preparing".equalsIgnoreCase(s) ? "Being prepared." :
                                            "Ready".equalsIgnoreCase(s) ? "Ready for pickup." : s );
      out.write("\n");
      out.write("                                    </span>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <p class=\"text-white\">No previous orders found.</p>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <p class=\"text-white\">No orders found.</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
      out.write("<!-- Tailwind CSS -->\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<!-- Footer -->\n");
      out.write("<footer class=\"bg-black text-white py-16 px-6 relative\">\n");
      out.write("  <div class=\"max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-10 animate-fadeInUp\">\n");
      out.write("\n");
      out.write("    <!-- Logo + Description -->\n");
      out.write("    <div>\n");
      out.write("      <h2 class=\"text-2xl font-bold mb-3\">FoodieCanteen</h2>\n");
      out.write("      <p class=\"text-gray-300\">Delivering hot, tasty meals to your doorstep. Quick. Reliable. Delicious.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Quick Links -->\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Explore</h3>\n");
      out.write("      <ul class=\"space-y-2 text-gray-300\">\n");
      out.write("        <li><a href=\"/menu\" class=\"hover:text-white transition\">Menu</a></li>\n");
      out.write("        <li><a href=\"/offers\" class=\"hover:text-white transition\">Offers</a></li>\n");
      out.write("        <li><a href=\"/track\" class=\"hover:text-white transition\">Track Order</a></li>\n");
      out.write("        <li><a href=\"/faq\" class=\"hover:text-white transition\">FAQ</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Contact Info -->\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Contact</h3>\n");
      out.write("      <p class=\"text-gray-300\">Email: Foodie@Canteen.com</p>\n");
      out.write("      <p class=\"text-gray-300\">Phone: +91 79878 40420</p>\n");
      out.write("      <p class=\"text-gray-300 mb-4\">Bhopal, India</p>\n");
      out.write("\n");
      out.write("      <!-- Payment Logos -->\n");
      out.write("      <div class=\"flex items-center space-x-3\">\n");
      out.write("        <img src=\"https://img.icons8.com/color/48/visa.png\" class=\"w-10 h-7\" alt=\"Visa\"/>\n");
      out.write("        <img src=\"https://img.icons8.com/color/48/mastercard.png\" class=\"w-10 h-7\" alt=\"MasterCard\"/>\n");
      out.write("        \n");
      out.write("        <img src=\"https://img.icons8.com/color/48/paypal.png\" class=\"w-10 h-7\" alt=\"PayPal\"/>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Newsletter + Social -->\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Stay Updated</h3>\n");
      out.write("      <form class=\"flex flex-col sm:flex-row gap-2\">\n");
      out.write("        <input type=\"email\" placeholder=\"Your email\"\n");
      out.write("               class=\"w-full px-4 py-2 rounded bg-gray-900 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-white\">\n");
      out.write("        <button type=\"submit\" class=\"bg-white text-black px-4 py-2 rounded hover:bg-gray-300 transition\">Subscribe</button>\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("       <div>\n");
      out.write("      <h3 class=\"text-xl font-semibold mb-4\">Follow Us</h3>\n");
      out.write("      <div class=\"flex gap-4\">\n");
      out.write("        <a href=\"#\" class=\"transform hover:scale-125 transition-transform duration-300\" data-aos=\"zoom-in\">\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/1384/1384063.png\" alt=\"Facebook\" class=\"w-8 h-8 hover:drop-shadow-[0_0_8px_#000000]\" />\n");
      out.write("        </a>\n");
      out.write("        <a href=\"#\" class=\"transform hover:scale-125 transition-transform duration-300\" data-aos=\"zoom-in\" data-aos-delay=\"100\">\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/1384/1384060.png\" alt=\"Instagram\" class=\"w-8 h-8 hover:drop-shadow-[0_0_8px_#000000]\" />\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Footer Bottom -->\n");
      out.write("  <div class=\"text-center text-gray-400 mt-12 border-t border-gray-700 pt-6\">\n");
      out.write("    &copy; 2025 <span class=\"text-white font-semibold\">FoodieCanteen</span> | Built with Love and hot samosas.\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Scroll To Top Button -->\n");
      out.write("  <button onclick=\"scrollToTop()\"\n");
      out.write("          class=\"fixed bottom-5 right-5 bg-white text-black p-3 rounded-full shadow-lg hover:bg-gray-200 hover:scale-110 transition duration-300 z-50\">\n");
      out.write("    <i class=\"fas fa-arrow-up\"></i>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <!-- Floating Chat Icon -->\n");
      out.write("  \n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Scroll to Top Script -->\n");
      out.write("<script>\n");
      out.write("function scrollToTop() {\n");
      out.write("  window.scrollTo({ top: 0, behavior: 'smooth' });\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- Fade-in Keyframes -->\n");
      out.write("<style>\n");
      out.write("@keyframes fadeInUp {\n");
      out.write("  from { opacity: 0; transform: translateY(40px); }\n");
      out.write("  to   { opacity: 1; transform: translateY(0); }\n");
      out.write("}\n");
      out.write(".animate-fadeInUp {\n");
      out.write("  animation: fadeInUp 1.2s ease-out both;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- FOOTER HTML \n");
      out.write("<footer class=\"footer\">\n");
      out.write("  <div class=\"footer-container\">\n");
      out.write("    <div class=\"footer-box about\">\n");
      out.write("      <h2 class=\"footer-title\">FoodDash</h2>\n");
      out.write("      <p>Delivering hot, tasty meals to your doorstep. Quick. Reliable. Delicious.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer-box links\">\n");
      out.write("      <h3>Explore</h3>\n");
      out.write("      <ul>\n");
      out.write("        <li><a href=\"/menu\">Our Menu</a></li>\n");
      out.write("        <li><a href=\"/offers\">Offers</a></li>\n");
      out.write("        <li><a href=\"/track\">Track Order</a></li>\n");
      out.write("        <li><a href=\"/faq\">FAQ</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer-box contact\">\n");
      out.write("      <h3>Contact</h3>\n");
      out.write("      <p>Email: hello@fooddash.com</p>\n");
      out.write("      <p>Phone: +91 98765 43210</p>\n");
      out.write("      <p>Delhi, India</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer-box social\">\n");
      out.write("      <h3>Follow Us</h3>\n");
      out.write("      <div class=\"social-icons\">\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-x-twitter\"></i></a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"footer-bottom\">\n");
      out.write("    &copy; 2025 <strong>FoodDash</strong> | Built with ? and hot samosas.\n");
      out.write("  </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write(" FONT AWESOME ICONS \n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write(" FOOTER CSS \n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("  margin: 0;\n");
      out.write("  background: #000;\n");
      out.write("  color: white;\n");
      out.write("  font-family: 'Segoe UI', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer {\n");
      out.write("  background: linear-gradient(145deg, #000000, #1a1a1a);\n");
      out.write("  color: #ffffff;\n");
      out.write("  padding: 60px 20px 30px;\n");
      out.write("  box-shadow: 0 -5px 30px rgba(255, 255, 255, 0.1);\n");
      out.write("  animation: fadeSlideUp 1.5s ease forwards;\n");
      out.write("  border-top: 2px solid #fff;\n");
      out.write("  position: relative;\n");
      out.write("  z-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-container {\n");
      out.write("  display: flex;\n");
      out.write("  flex-wrap: wrap;\n");
      out.write("  justify-content: space-around;\n");
      out.write("  max-width: 1200px;\n");
      out.write("  margin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box {\n");
      out.write("  flex: 1 1 220px;\n");
      out.write("  margin: 20px;\n");
      out.write("  transform: translateY(30px);\n");
      out.write("  animation: slideUp 1s ease forwards;\n");
      out.write("  opacity: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box:nth-child(1) { animation-delay: 0.2s; }\n");
      out.write(".footer-box:nth-child(2) { animation-delay: 0.4s; }\n");
      out.write(".footer-box:nth-child(3) { animation-delay: 0.6s; }\n");
      out.write(".footer-box:nth-child(4) { animation-delay: 0.8s; }\n");
      out.write("\n");
      out.write(".footer-title {\n");
      out.write("  font-size: 26px;\n");
      out.write("  color: #ffffff;\n");
      out.write("  margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box h3 {\n");
      out.write("  color: #ffffff;\n");
      out.write("  font-size: 18px;\n");
      out.write("  margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul {\n");
      out.write("  list-style: none;\n");
      out.write("  padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul li {\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul li a {\n");
      out.write("  color: #bbb;\n");
      out.write("  text-decoration: none;\n");
      out.write("  transition: 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box ul li a:hover {\n");
      out.write("  color: #fff;\n");
      out.write("  text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-box p {\n");
      out.write("  color: #ccc;\n");
      out.write("  line-height: 1.6;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-icons a {\n");
      out.write("  color: #fff;\n");
      out.write("  margin-right: 15px;\n");
      out.write("  font-size: 20px;\n");
      out.write("  transition: transform 0.3s ease, color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-icons a:hover {\n");
      out.write("  color: #fff;\n");
      out.write("  transform: scale(1.3) rotate(5deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-bottom {\n");
      out.write("  text-align: center;\n");
      out.write("  margin-top: 40px;\n");
      out.write("  padding-top: 15px;\n");
      out.write("  border-top: 1px solid #444;\n");
      out.write("  font-size: 14px;\n");
      out.write("  color: #aaa;\n");
      out.write("  opacity: 0.8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes fadeSlideUp {\n");
      out.write("  from {\n");
      out.write("    opacity: 0;\n");
      out.write("    transform: translateY(40px);\n");
      out.write("  }\n");
      out.write("  to {\n");
      out.write("    opacity: 1;\n");
      out.write("    transform: translateY(0);\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes slideUp {\n");
      out.write("  to {\n");
      out.write("    transform: translateY(0);\n");
      out.write("    opacity: 1;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 768px) {\n");
      out.write("  .footer-container {\n");
      out.write("    flex-direction: column;\n");
      out.write("    align-items: center;\n");
      out.write("    text-align: center;\n");
      out.write("  }\n");
      out.write("  .footer-box {\n");
      out.write("    margin: 20px 0;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("</style>-->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
